ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS dietary_preference VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS personality_type VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS trip_category VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS lactose_intolerant BOOLEAN;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS drinks_alcohol BOOLEAN;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS smokes BOOLEAN;
